# Generated by Django 3.1.7 on 2021-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='totalquestion',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
